# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ZQSubject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZQSubject
  
  # Swift
  pod 'Moya'                          #网络请求
  pod 'IQKeyboardManagerSwift'        #键盘遮挡上移
  pod 'SnapKit'                       #约束布局
  pod 'Kingfisher'                    #加载网络图片
  pod 'FSPagerView'                   #轮播图
  pod 'MarqueeLabel'                  #跑马灯
  pod 'DeviceKit', '~> 5.2'           #设备信息
  pod 'ReachabilitySwift'             #网络状态
  
  pod 'CocoaLumberjack/Swift'         #日志管理
  pod 'SwiftyJSON'                    #JSON数据处理
  
  pod 'Then'                          #初始化语法糖
  #数据库
#  pod 'RealmSwift'
  #加密
  pod 'CryptoSwift'
  
  #响应式编程
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Objective-C
  pod 'MJRefresh'                     #上下拉刷新

  #MBProgressHUD的PrivacyInfo
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git'
  # 分页控制器
  pod 'WMZPageController'
  pod 'JLRoutes'                      #路由管理
  
  pod 'UITextView+Placeholder'
  
  #推送 友盟
#  pod 'UMCommon'
#  pod 'UMDevice'
#  pod 'UMCCommonLog', :configurations => ['Debug']
#  pod 'UMPush'
#  pod 'UYuMao'
  
  #极光
  pod 'JPush'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
